var Activity = {
		ZERO: 0,
		INICIO: 4,
		LANCAR_NOTA: 111,
		CONFERENCIA_FINANCEIRO: 16,
		AVALIAR_CONTROLADORIA: 19,
		AVALIAR_DIRETOR_GERAL: 31,
		GATEWAY_ENVOLVE_DIRETOR_FINANCEIRO: 78,
		AVALIAR_DIRETOR_FINANCEIRO: 33,
		GATEWAY_ENVOLVE_PRESIDENTE: 43,
		AVALIAR_PRESIDENTE: 35,
		DEFINIR_CONTA_PA: 89,
		SERVICE_TITULO_PAGAR: 65,
		VERIFICAR_SITUACAO: 69,
		RECEBIDO_CONFERIDO: 52,
		GATEWAY_CORRIGIR: 94,
		FIM_PAGO: 40
};