var Activity = {
	ZERO: 0,
	INICIO: 4,
	SOLICITAR_PARECER: 75,
	AVALIAR_GER_AREA: 20,
	AVALIAR_DIR_AREA: 22,
	AVALIAR_JURIDICO: 26,
	AVALIAR_CONTROLADORIA: 30,
	AVALIAR_GER_FINANCEIRO: 33,
	AVALIAR_DIR_FINANCEIRO: 34,
	AVALIAR_PRESIDENTE: 35,
	CONFERENCIA_JURIDICA: 53,
	FIM: 17
	
};